export const ADD_ANGER_REQUEST = 'ADD_ANGER_REQUEST';
export const ADD_ANGER_SUCCESS = 'ADD_ANGER_SUCCESS';
export const ADD_ANGER_ERROR = 'ADD_ANGER_ERROR';

export const GET_ANGER_REQUEST = 'GET_ANGER_REQUEST';
export const GET_ANGER_SUCCESS = 'GET_ANGER_SUCCESS';
export const GET_ANGER_ERROR = 'GET_ANGER_ERROR';