export const ADD_SPEND_REQUEST = 'ADD_SPEND_REQUEST';
export const ADD_SPEND_SUCCESS = 'ADD_SPEND_SUCCESS';
export const ADD_SPEND_ERROR = 'ADD_SPEND_ERROR';

export const GET_SPEND_REQUEST = 'GET_SPEND_REQUEST';
export const GET_SPEND_SUCCESS = 'GET_SPEND_SUCCESS';
export const GET_SPEND_ERROR = 'GET_SPEND_ERROR';